name: Java Param called from diff Repo

on:
  workflow_call:
    inputs:
      java_version:
        description: 'JDK version to use (default: 17)'
        required: true
        default: '17'
        type: string
      maven_directory:
        description: 'Directory of the Java Maven project (default: ./java-app)'
        required: true
        default: './java-app'
        type: string

permissions:
  security-events: write
  contents: read
  actions: read
  checks: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package
      working-directory: ${{ inputs.maven_directory }}
      
  # CodeQL Scanning job
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
        build-mode: autobuild

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        output: codeql-results.sarif

#endoffile
