name: Calling Java Workflow from a Different Repo

on:
  workflow_dispatch:

jobs:
  Call-Java-Workflow-in-Different-Repo:
    uses: Sora-fication/project-fication/.github/workflows/parameterized-java.yml@main
    with:
      java_version: '17'
      maven_directory: './java-app'
